### ISSUE TITLE
Assumed directory structure for location of hello_pi libraries

### ISSUE THREAD

**Issue by shortbloke** [luyi1888/ctxh264_pi#2]
I'm somewhat new to this, so not sure if these suggestions are best made as pull requests, or some other means. Please let me know.

Looking at the Makefile.include, the path to ilclient and vgfont is expected to be a level above the project directory, this may not be the case. Since these files AFAIK are present in the Raspbian image at a known location wouldn't updating the path to include this defined location making building of this project easier for others that may not share the same directory layout as you?

```
LDFLAGS+=-L$(SDKSTAGE)/opt/vc/lib/ -lEGL -lGLESv2 -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpthread -lrt -lm -L../libs/ilclient -L../libs/vgfont

INCLUDES+=-I$(SDKSTAGE)/opt/vc/include/ -I$(SDKSTAGE)/opt/vc/include/interface/vcos/pthreads -I$(SDKSTAGE)/opt/vc/include/interface/vmcs_host/linux -I./ -I../libs/ilclient -I../libs/vgfont
```

could be replaced  by:

```
LDFLAGS+=-L$(SDKSTAGE)/opt/vc/lib/ -lEGL -lGLESv2 -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpthread -lrt -lm -L/opt/vc/src/hello_pi/libs/ilclient -L/opt/vc/src/hello_pi/libs/vgfont

INCLUDES+=-I$(SDKSTAGE)/opt/vc/include/ -I$(SDKSTAGE)/opt/vc/include/interface/vcos/pthreads -I$(SDKSTAGE)/opt/vc/include/interface/vmcs_host/linux -I./ -I$(SDKSTAGE)/opt/vc/src/hello_pi/libs/ilclient -I$(SDKSTAGE)/opt/vc/src/hello_pi/libs/vgfont
```

**Comment by luyi1888** [comment]
Thanks.
fixed in commit 4e2cca8e3cd8dd2f01a8a71da4cd7a6dbb34fa35
